version: '3'

volumes:
  School_lf8_starter_postgres_data:
    driver: local

services:
  postgres_for_School_lf8_starter:
    container_name: School_lf8_starter_postgres_container
    image: postgres:16.4
    volumes:
      - School_lf8_starter_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lf8_starter_db
      POSTGRES_USER: lf8_starter
      POSTGRES_PASSWORD: secret
    ports:
      - "15369:5432"